import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import HomeIcon from '@mui/icons-material/Home';
import { AppBar, Toolbar, IconButton, Typography, Button, Container } from '@material-ui/core'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CV BUILDER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Container>

      <AppBar position="static">
        <Toolbar>
          <IconButton edge="start" color="inherit" aria-label="menu">
          <Link href='/'>
            <HomeIcon />
          </Link>
          </IconButton>
          <Typography variant="h6" >
            <Link href='/sobre'>
              Sobre  
            </Link>
          </Typography>

          <Typography variant="h6" >
            <Link href='/dicas'>
              Dicas  
            </Link>
          </Typography>


          <Typography variant="h6" >
            <Link href='/builder'>
              builder  
            </Link>
          </Typography>

        </Toolbar>
      </AppBar>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to your CV builder.
        </h1>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Container>
    </div>
  )
}

export default Home
